-- Phase 2.1 Monetization M1: DB scaffolding for beta onboarding

-- 0) Optional: track beta testers (onboard ~100 testers)
CREATE TABLE IF NOT EXISTS public.beta_testers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL, -- 'athlete'|'parent'|'coach'|'media'
  invited_at timestamptz NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'pending' -- 'pending'|'active'
);

-- 1) token_items (pricing and item definitions)
CREATE TABLE IF NOT EXISTS public.token_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,              -- 'spotlight' | 'ad_banner' | 'vote' | etc
  cost_tokens INTEGER NOT NULL,
  description TEXT,
  duration_days INTEGER,
  active BOOLEAN DEFAULT TRUE,
  created_at timestamptz NOT NULL DEFAULT now()
);
