-- Phase 2: Monetization: token edit, token pricing, freebies, spotlight edit
--
-- token_edits (denotes someone spotlight edit a token)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.token_items WHERE name = 'SpotLight Edit' AND type = 'spotLight'
  ) THEN
    INSERT INTO public.token_items (name, type)
    VALUES ('SpotLight Edit', 'spotLight');
  END IF;
END $$;

-- token_accounts, token_purchases (denotes token purchase; schema: independent)
CREATE TABLE IF NOT EXISTS public.token_accounts (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.token_purchases (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  token_item_id UUID NOT NULL REFERENCES public.token_items(id),
  stripe_session_id TEXT
);
-- Phase 2.1 Monetization M1: DB scaffolding for beta onboarding (continued)

-- 1a) Index for token_items
CREATE INDEX IF NOT EXISTS idx_token_items_name ON public.token_items(name);

-- 2) token_accounts (wallet per user)
CREATE TABLE IF NOT EXISTS public.token_accounts (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  balance INTEGER NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 3) token_purchases
CREATE TABLE IF NOT EXISTS public.token_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  tokens INTEGER NOT NULL,
  amount_currency TEXT,
  amount_value NUMERIC,
  stripe_session_id TEXT,
  purchased_at timestamptz NOT NULL DEFAULT now()
);
