-- Phase 2.1 Monetization: token wallet, two-tier pricing, freebies, spotlight/ads

-- 1) token_items (ensure Spotlight Edit exists; if not, create)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.token_items WHERE name = 'Spotlight Edit' AND type = 'spotlight'
  ) THEN
    INSERT INTO public.token_items (name, type, cost_tokens, description, duration_days, active)
    VALUES ('Spotlight Edit', 'spotlight', 60, 'Token-based Spotlight Edit (promo poster) with optional pin/share', 7, true);
  END IF;
END $$;

-- 2) token_accounts, token_purchases, token_spends (basic schema; idempotent)
CREATE TABLE IF NOT EXISTS public.token_accounts (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE cascade,
  balance INTEGER NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.token_purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  tokens INTEGER NOT NULL,
  amount_currency TEXT,
  amount_value NUMERIC,
  stripe_session_id TEXT,
  purchased_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.token_spends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES public.token_items(id) ON DELETE SET NULL,
  tokens_spent INTEGER NOT NULL,
  activity_id TEXT,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3) Free allocations (existence safe)
CREATE TABLE IF NOT EXISTS public.spotlight_free_allocations_team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  consumed BOOLEAN DEFAULT FALSE,
  consumed_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.spotlight_free_allocations_org (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  consumed BOOLEAN DEFAULT FALSE,
  consumed_at timestamptz
);

-- 4) Spotlight edits (existing core table kept; ensure we can link free allocations)
ALTER TABLE IF EXISTS public.spotlight_edits
  ADD COLUMN IF NOT EXISTS allocated_by_pipeline BOOLEAN DEFAULT FALSE;

ALTER TABLE public.spotlight_edits
  ALTER COLUMN pinned SET DEFAULT FALSE;

-- 5) Ad-related tables (optional MVP extension)
CREATE TABLE IF NOT EXISTS public.ad_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advertiser_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  region TEXT,
  type TEXT,
  start_date DATE,
  end_date DATE,
  price_tokens INTEGER,
  creative_url TEXT,
  link_url TEXT,
  status TEXT DEFAULT 'draft'
);

CREATE TABLE IF NOT EXISTS public.ad_impressions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT REFERENCES public.ad_campaigns(id) ON DELETE CASCADE,
  timestamp timestamptz DEFAULT now(),
  athlete_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  location TEXT
);
